### PR TITLE
Initial Research

### PR DESCRIPTION
**Pull request by asarode**
Open Questions:
- [x] Should the game server be peer-to-peer or authoritative? <strong>Authoritative server</strong>
- [x] What language and framework should we use? <strong>Elixir with Phoenix</strong>
- [ ] How should we handle the networking layer? With TCP or Phoenix channels? <strong>Proposing TCP</strong>
- [ ] How should we send state updates? <strong>with deltas?</strong>

Important Links:
- [Learn Elixir from their getting started guide](http://elixir-lang.org/getting-started/introduction.html)
- [Explore Phoenix](http://www.phoenixframework.org/docs/overview)

### CODE REVIEW

**Comment by KyleBWilson49** [comment]
Hex grid, pathing becomes simple. for right now simple straight path using hex grid. towers have tile range. Towers hit minion that is closest to the end of its path.

**Comment by asarode** [comment]
Are towers on the same hex grid as the minions? Is 1 hex grid the smallest unit of measurement in the state, or is there a smaller unit? In the case of a smaller unit, 1 hex grid is x units long. Otherwise each hex grid is one coordinate point. So which one?

**Comment by asarode** [comment]
Woops, accidental close. My bad.

**Comment by KyleBWilson49** [comment]
Back end keeps track of board state, each space can contain the object of whatever is on that tile.

**Comment by KyleBWilson49** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjxlNjHkpHMAhUI_mMKHS_jAF8QjRwIBw&url=http%3A%2F%2Fvividgamer.com%2F2012%2F08%2F24%2Ftower-wars-review%2F&psig=AFQjCNGDwxR6wmGfRS4BC1uZSjYHBQthAA&ust=1460826936682739

**Comment by kuhasuki** [comment]
We did it!
http://www.redblobgames.com/grids/hexagons/

**Comment by asarode** [comment]
Here's a very good high level overview of different multiplayer networking techniques: http://gafferongames.com/networking-for-game-programmers/what-every-programmer-needs-to-know-about-game-networking/
The last one it mentions is the one I'm proposing we use. Looks like the most fun to implement.

**Comment by kuhasuki** [comment]
https://www.assetstore.unity3d.com/en/#!/content/5106

Tower defense game assets

**Comment by KyleBWilson49** [comment]
http://opengameart.org/content/isometric-road-tiles

**Comment by asarode** [comment]
UI style that I think we might be able to pull off:
- http://i.imgur.com/v1oX9WI.png
- http://code-beans.com/UltimateIsometricToolkit/img/world.png
- https://s-media-cache-ak0.pinimg.com/originals/9c/3e/7f/9c3e7f5c9a08d653e25719c2ae275939.png
- http://i.imgur.com/uSkDi40.png

**Comment by asarode** [comment]
https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking

**Comment by asarode** [comment]
http://www.gamedev.net/index.php?app=forums&module=forums&section=rules&f=15

"Q3) Should I use TCP or UDP?
A3) There are at least four different kinds of games as far as networking is concerned: Turn-based games, Real Time Strategy games, Role Playing Games, and Action Games. Briefly, if you're turn-based, you should go with TCP because it's simpler, unless you need peer-to-peer NAT punch-through. For RTS games, you're usually best off using TCP, although UDP can make sense in extreme cases. For role playing games, the story is less clear -- action-based RPGs with lots of kinetics, like City of Heroes, use UDP, whereas slower RPGs and MUDs often stay with TCP. For action-based games like first-person shooters or racers, you should absolutely use UDP."

**Comment by asarode** [comment]
I'm proposing that we use an [entity component system](https://en.wikipedia.org/wiki/Entity_component_system) called Entitas. It lets you decouple your state from Unity, and it makes a ton of sense if you gel with the idea of monolithic state and state changes contained in specific functions/scripts.

Here's a video overview about how it all works: https://www.youtube.com/watch?v=1wvMXur19M4
Here's the repo: https://github.com/sschmid/Entitas-CSharp

**Comment by KyleBWilson49** [comment]
https://www.raywenderlich.com/107525/create-tower-defense-game-unity-part-1

td tutorial in unity

**Comment by asarode** [comment]
Some nice game dev related subreddits:
- [r/gamedev](https://www.reddit.com/r/gamedev/): About game dev in general
- [r/gamedevscreens](https://www.reddit.com/r/gamedevscreens/): Screenshots from work in progress games
- [r/TheMakingOfGames](https://www.reddit.com/r/TheMakingOfGames): Videos/articles about the process different dev teams use for building games

**Comment by asarode** [comment]
Another high level explanation of the authoritative server model we'll (hopefully) be using: http://gafferongames.com/2016/04/25/never-trust-the-client/

**Pull request closed without merging**
